djangoPro/urls.py
from django.contrib import admin
from django.urls import path, include
from scuser.views import index, RegisterView, LoginView, logout
from product.views import ProductList,ProductCreate,ProductDetail,ProductListAPI,ProductDetailAPI
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('register/',RegisterView.as_view()),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', logout,name='logout'),
    path('product/',ProductList.as_view(),name ='productList'),
    path('product/<int:pk>/',ProductDetail.as_view()),
    path('product/create/',ProductCreate.as_view(),name ='productCreate'),
    path('order/',OrderList.as_view(),name='order'),
    path('order/create/',OrderCreate.as_view(),name='orderCreate'),

    path('api/product/',ProductListAPI.as_view()),
    path('api/product/<int:pk>/',ProductDetailAPI.as_view()),


]

sc_django/sc_django/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

]

product/models.py
from django.db import models
from django.views.generic import ListView


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stuck = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'sccampus_product'
        verbose_name = '상품'
        verbose_name_plural = '상품'


class ProList(ListView):
    model = Product
    paginate_by = 6

product/forms.py
from django import forms
from .models import Product


class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        },
        max_length=64, label='상품명'
    )

    price = forms.IntegerField(
        error_messages={
            'required' : '상품가격을 입력해주세요.'
        }, label='상품가격'
    )

    description = forms.CharField(
        error_messages={
            'required' : '상품명을 입력해주세요.'
        }, label='상품명'
    )
    stuck = forms.IntegerField(
        error_messages={
            'required' : '재고를 입력해주세요.'
        }, label='재고'
    )


    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stuck = cleaned_data.get('stuck')

        if not(name and price and description and stuck):
            self.add_error('name', '값이 없습니다.')
            self.add_error('price', '값이 없습니다.')

product/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from rest_framework import generics
from rest_framework import mixins

from django.views.generic import ListView,DeleteView
from django.views.generic.edit import FormView
from scuser.decorators import login_required, admin_required
from .models import Product
from .forms import RegisterForm
from order.forms import RegisterForm as OrderForm
from .serializers import ProductSerializer


class ProductListAPI(generics.GenericAPIView,mixins.ListModelMixin):
    serializer_class = ProductSerializer
    def get_queryset(self):
        return Product.objects.all().order_by('id')
    def get(self,request,*args,**kwargs):
        return self.list(request,*args,**kwargs)

#mixins.RetrieveModelMixin상세보기를 위한 모델
class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer
    def get_queryset(self):
        return Product.objects.all().order_by('id')
    def get(self,request,*args,**kwargs):
        return self.retrieve(request,*args,**kwargs)


class ProductList(ListView):
    model = Product
    paginate_by = 6
    template_name = 'product.html'
    context_object_name = 'product_list'

    #페이지네이션 커스텀
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page -1 )/ page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        return context



@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    model = Product
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stuck=form.data.get('stuck')
        )
        product.save()
        return super().form_valid(form)


class ProductDetail(DeleteView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

product/templates/index.html
{% extends "base.html" %}

{% block contents %}


  <div class="jumbotron">
  <h1 class="display-3">"{{ email }}"<h3>님 로그인 되셨습니다.</h3></h1>
  <p class="lead">SC쇼핑몰에 오신 것을 환영합니다.</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'productList' %}" role="button">
        물품보기</a>
  </p>
</div>




{% endblock %}

product/templates/login.html
{% extends "base.html" %}

{% block contents %}
<div class ="row mt-5">
    <div class="col-12 text-center">
        <h1>로그인</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="post" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for = "{{ field.id_for_label }}">{{ field.label }}</label>
                <input type="{{ field.field.widget.input_type }}" class="form-control"
                id="{{ field.id_for_label }}" placeholder="{{ field.label }}"
                       name="{{ field.name }}" />
            </div>
            {% if field.errors %}
            <span style="color: rebeccapurple">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">login</button>
        </form>
    </div>
</div>
{% endblock %}

product/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% block header %}
<script>
 function product_detail(id) {
        $.ajax({
          url: "/api/product/" + id,
           success: function (result) {
            $("#product-" + id).popover({
                html: true,
                content: result.name + "<br/>" + result.price
            }).popover('show');
          }
        });
 }
function product_leave(id){
     $("#product-" + id).popover('hide');
 }
 $(document).ready(function (){});
</script>
{% endblock %}
{% block contents %}
 <div class="row mt-5">
  <div class="col-12">
   <table class="table table-secondary">
       <thead class="table-primary">
       <tr>
           <th scope="col">#</th>
           <th scope="col">상품명</th>
           <th scope="col">가 격</th>
           <th scope="col">등록날짜</th>
       </tr>
       </thead>
       <tbody class="text-dark">
        {% for product in object_list %}
        <tr>
            <th scope="row">{{ product.id }}</th>
            <th><a id="product-{{ product.id }}"
                   onmouseenter="product_detail({{ product.id }});" onmouseleave="product_leave({{ product.id  }});"
                   href="/product/{{ product.id }}">{{ product.name }}</a></th>
            <th>{{ product.price|intcomma }}원</th>
            <th >{{ product.register_date|date:'Y-m-d H:i' }}</th>
        </tr>
       {% endfor %}
       </tbody>
   </table>
 </div>


 {% if is_paginated %}
 <div>
  <ul class="pagination pagination-lg">
    {% if page_obj.has_previous %}
    <li class="page-item active">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}"tabindex="-1">이전</a>
    </li>
    {% else %}
     <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">이전</a>
     </li>
    {% endif %}


    {% for page in page_range %}
    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
      <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endfor %}

     {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
 {% endif %}
 </div>



</div>
{% endblock %}

product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block header %}
{% endblock %}

{% block contents %}
<div class="row mt-5">
 <div class="col-12">
   <div class="card text-white bg-secondary mb-3" style="width: 100%;">
      <div class="card-body">
       <h5 class="card-title">{{ product.name }}</h5>
      </div>
       <ul class="list-group list-group-flush">
           <li class="list-group-item">
               <form method="POST" action="/order/create/">
               {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                      {% ifnotequal field.name 'product' %}
                        <label for = "{{ field.id_for_label }}">{{ field.label }}</label>
                      {% endifnotequal %}
                        <input type="{{ field.field.widget.input_type }}" class="form-control"
                               id="{{ field.id_for_label }}" placeholder="{{ field.label }}"
                               name="{{ field.name }}"
                               value="{% ifequal field.name 'product' %}{{ product.id }}{% endifequal %} "/>
            </div>
            {% if field.errors %}
            <span style="color:crimson ">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">주문하기</button>

               </form>
           </li>
           <li class="list-group-item">가격: {{ product.price|intcomma }}원</li>
           <li class="list-group-item">등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}</li>
           <li class="list-group-item">재고: {{ product.stuck  }} 개</li>
           <li class="list-group-item">{{ product.description|safe }}</li>
       </ul>
   </div>
<div class="row">
    <div class="col-12">
        <a href="/product/">목록보기</a>
    </div>
</div>

 </div>
</div>
{% endblock %}

product/templates/register.html
{% extends "base.html" %}

{% block contents %}
<div class ="row mt-5">
    <div class="col-12 text-center">
        <h1>회원가입</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="post" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for = "{{ field.id_for_label }}">{{ field.label }}</label>
                <input type="{{ field.field.widget.input_type }}" class="form-control"
                id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}" />
            </div>
            {% if field.errors %}
            <span style="color: rebeccapurple">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">가입하기</button>
        </form>
    </div>
</div>
{% endblock %}

product/templates/register_product.html
{% extends "base.html" %}
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css"
      rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_description').summernote({
            height:300
        });
    });
  </script>
{% endblock %}
{% block contents %}
<div class ="row mt-5">
    <div class="col-12 text-center">
        <h1>상품 생성하기</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="post" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for = "{{ field.id_for_label }}">{{ field.label }}</label>
                {% ifequal field.name 'description' %}
                <textarea class="form-control" name = "{{ field.name }}"
                          id="{{  field.id_for_label }}"></textarea>

                {% else %}
                <input type="{{ field.field.widget.input_type }}" class="form-control"
                  id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}" />
                {% endifequal %}
            </div>
            {% if field.errors %}
            <span style="color: rebeccapurple">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">생성완료</button>
        </form>
    </div>
</div>
{% endblock %}